//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IClone.ICloneImplementation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICloneLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICloneLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("IClone.ICloneImplementation.ICloneLocalization", typeof(ICloneLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Версия {0}.
        /// </summary>
        internal static string ABOUT_VersionLabelText {
            get {
                return ResourceManager.GetString("ABOUT_VersionLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to О программе &quot;{0}&quot;.
        /// </summary>
        internal static string ABOUT_WindowHeader {
            get {
                return ResourceManager.GetString("ABOUT_WindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Файлов обработано.
        /// </summary>
        internal static string CMN_FileProcessedNameLabelText {
            get {
                return ResourceManager.GetString("CMN_FileProcessedNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строк обработано.
        /// </summary>
        internal static string CMN_RowsProcessedNameLabelText {
            get {
                return ResourceManager.GetString("CMN_RowsProcessedNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прошло времени.
        /// </summary>
        internal static string CMN_TimeElapsedNameLabelText {
            get {
                return ResourceManager.GetString("CMN_TimeElapsedNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Токенов обработано.
        /// </summary>
        internal static string CMN_TokensProcessedNameLabelText {
            get {
                return ResourceManager.GetString("CMN_TokensProcessedNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Количество вычислительных ядер недостаточно для эффективной работы библиотеки параллельных задач. Рекомендуется отключить эту опцию.
        /// </summary>
        internal static string CMNMESS_CannotUseParallelExtensions {
            get {
                return ResourceManager.GetString("CMNMESS_CannotUseParallelExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран ни один языковой плагин.
        /// </summary>
        internal static string CMNMESS_NoOnePluginChoosen {
            get {
                return ResourceManager.GetString("CMNMESS_NoOnePluginChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции прервано пользователем.
        /// </summary>
        internal static string CMNMESS_OperationCancelled {
            get {
                return ResourceManager.GetString("CMNMESS_OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите, идёт прерывание операции.
        /// </summary>
        internal static string CMNMESS_OperationCancellingInProgress {
            get {
                return ResourceManager.GetString("CMNMESS_OperationCancellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции успешно завершено.
        /// </summary>
        internal static string CMNMESS_OperationDoneSuccesfully {
            get {
                return ResourceManager.GetString("CMNMESS_OperationDoneSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт выполнение операции.
        /// </summary>
        internal static string CMNMESS_OperationInProgress {
            get {
                return ResourceManager.GetString("CMNMESS_OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции завершено с ошибками.
        /// </summary>
        internal static string CMNMESS_OperationtDoneWithErrors {
            get {
                return ResourceManager.GetString("CMNMESS_OperationtDoneWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось загрузить ни одного плагина. Возможно переустановка приложения позволит решить проблему.
        /// </summary>
        internal static string CMNMESS_PluginsNotAvailable {
            get {
                return ResourceManager.GetString("CMNMESS_PluginsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ожидание действий пользователя.
        /// </summary>
        internal static string CMNMESS_WaitingForUserActions {
            get {
                return ResourceManager.GetString("CMNMESS_WaitingForUserActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to В текущей версии данная функциональность не поддерживается. Следите за обновлениями..
        /// </summary>
        internal static string CNMMESS_FunctionalityNotSupported {
            get {
                return ResourceManager.GetString("CNMMESS_FunctionalityNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неверный параметр командной строки. Приложение будет запущено в оконном режиме..
        /// </summary>
        internal static string CNMMESS_InvalidCommandLineArgument {
            get {
                return ResourceManager.GetString("CNMMESS_InvalidCommandLineArgument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Для получения более широких возможностей используйте оконный режим работы приложения.
        /// </summary>
        internal static string CONSOLE_UseGUIModeMessage {
            get {
                return ResourceManager.GetString("CONSOLE_UseGUIModeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Нажмите любую клавишу для продолжения....
        /// </summary>
        internal static string CONSOLE_WaitingMessage {
            get {
                return ResourceManager.GetString("CONSOLE_WaitingMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Алгоритм для поиска клонов.
        /// </summary>
        internal static string CSW_ChooseAlgorithmLabelText {
            get {
                return ResourceManager.GetString("CSW_ChooseAlgorithmLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбор каталога.
        /// </summary>
        internal static string CSW_ChooseCodeLocationButtonText {
            get {
                return ResourceManager.GetString("CSW_ChooseCodeLocationButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры поиска.
        /// </summary>
        internal static string CSW_CloneSearchTabPage1Text {
            get {
                return ResourceManager.GetString("CSW_CloneSearchTabPage1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Результаты поиска.
        /// </summary>
        internal static string CSW_CloneSearchTabPage2Text {
            get {
                return ResourceManager.GetString("CSW_CloneSearchTabPage2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Кодировка исходных файлов.
        /// </summary>
        internal static string CSW_CodeEncodingLabelText {
            get {
                return ResourceManager.GetString("CSW_CodeEncodingLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык программирования.
        /// </summary>
        internal static string CSW_CodeLanguageLabelText {
            get {
                return ResourceManager.GetString("CSW_CodeLanguageLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходный код.
        /// </summary>
        internal static string CSW_CodeLocationGroupBoxText {
            get {
                return ResourceManager.GetString("CSW_CodeLocationGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расположение исходных файлов.
        /// </summary>
        internal static string CSW_CodeLocationLabelText {
            get {
                return ResourceManager.GetString("CSW_CodeLocationLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прогресс выполнения.
        /// </summary>
        internal static string CSW_CodeProcessingResultsGroupBoxText {
            get {
                return ResourceManager.GetString("CSW_CodeProcessingResultsGroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строк в измененных файлах.
        /// </summary>
        internal static string CSW_RowsInModifiedFilesNameLabelText {
            get {
                return ResourceManager.GetString("CSW_RowsInModifiedFilesNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Строк в оригинальных файлах.
        /// </summary>
        internal static string CSW_RowsInOriginalFilesNameLabelText {
            get {
                return ResourceManager.GetString("CSW_RowsInOriginalFilesNameLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Начать поиск.
        /// </summary>
        internal static string CSW_StartCloneSearchButtonText {
            get {
                return ResourceManager.GetString("CSW_StartCloneSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Прервать.
        /// </summary>
        internal static string CSW_StopCloneSearchButtonText {
            get {
                return ResourceManager.GetString("CSW_StopCloneSearchButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск клонов.
        /// </summary>
        internal static string CSW_WindowHeader {
            get {
                return ResourceManager.GetString("CSW_WindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать хотя бы одно расширение файлов.
        /// </summary>
        internal static string DCS_ChooseFilesExtensions_Empty {
            get {
                return ResourceManager.GetString("DCS_ChooseFilesExtensions_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать директорию для поиска файлов.
        /// </summary>
        internal static string DCS_ChooseFolderError_Empty {
            get {
                return ResourceManager.GetString("DCS_ChooseFolderError_Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Необходимо указать существующую директорию.
        /// </summary>
        internal static string DCS_ChooseFolderError_NoneExist {
            get {
                return ResourceManager.GetString("DCS_ChooseFolderError_NoneExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выбранная директория для поиска файлов с исходным кодом.
        /// </summary>
        internal static string DCS_ChooseFolderLabelText {
            get {
                return ResourceManager.GetString("DCS_ChooseFolderLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Расширения файлов, по которым будет осуществлён поиск.
        /// </summary>
        internal static string DCS_ChoosenFileExtLabelText {
            get {
                return ResourceManager.GetString("DCS_ChoosenFileExtLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка объёма программного кода.
        /// </summary>
        internal static string DCS_WindowHeader {
            get {
                return ResourceManager.GetString("DCS_WindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры выполнения процедуры.
        /// </summary>
        internal static string GUI_CMN_GroupBoxText {
            get {
                return ResourceManager.GetString("GUI_CMN_GroupBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Использовать библиотеку параллельных задач.
        /// </summary>
        internal static string GUI_CMN_IsUseParallelExtensionsCheckBoxText {
            get {
                return ResourceManager.GetString("GUI_CMN_IsUseParallelExtensionsCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Запоминать параметры последнего запуска процедуры.
        /// </summary>
        internal static string GUI_CMN_MemorizeLastRunParamsCheckBoxText {
            get {
                return ResourceManager.GetString("GUI_CMN_MemorizeLastRunParamsCheckBoxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Язык.
        /// </summary>
        internal static string GUI_CMNOP_ChooseUILangLabelText {
            get {
                return ResourceManager.GetString("GUI_CMNOP_ChooseUILangLabelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Список каталогов, которые не нужно обрабатывать.
        /// </summary>
        internal static string GUI_CSW_SkippingFoldersLabelNameText {
            get {
                return ResourceManager.GetString("GUI_CSW_SkippingFoldersLabelNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общие.
        /// </summary>
        internal static string ICOP_ICloneCommonOptionsName {
            get {
                return ResourceManager.GetString("ICOP_ICloneCommonOptionsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        internal static string ICOP_ICloneOpCancelButtonText {
            get {
                return ResourceManager.GetString("ICOP_ICloneOpCancelButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ОК.
        /// </summary>
        internal static string ICOP_ICloneOpOKButtonText {
            get {
                return ResourceManager.GetString("ICOP_ICloneOpOKButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Применить.
        /// </summary>
        internal static string ICOP_ICloneOpSaveButtonText {
            get {
                return ResourceManager.GetString("ICOP_ICloneOpSaveButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        internal static string ICOP_OptionsTreeHeader {
            get {
                return ResourceManager.GetString("ICOP_OptionsTreeHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройка параметров приложения.
        /// </summary>
        internal static string ICOP_OptionsTreeHeaderTag {
            get {
                return ResourceManager.GetString("ICOP_OptionsTreeHeaderTag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки программы.
        /// </summary>
        internal static string ICOP_WindowHeader {
            get {
                return ResourceManager.GetString("ICOP_WindowHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Оценка объёма кода.
        /// </summary>
        internal static string MW_DCSMenuItemName {
            get {
                return ResourceManager.GetString("MW_DCSMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаление SVN-файлов.
        /// </summary>
        internal static string MW_DSSFMenuItemName {
            get {
                return ResourceManager.GetString("MW_DSSFMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справка.
        /// </summary>
        internal static string MW_HelpMenuItemName {
            get {
                return ResourceManager.GetString("MW_HelpMenuItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Главное окно.
        /// </summary>
        internal static string MW_WindowHeader {
            get {
                return ResourceManager.GetString("MW_WindowHeader", resourceCulture);
            }
        }
    }
}
