//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ICloneServices {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ICloneServicesLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ICloneServicesLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ICloneServices.ICloneServicesLocalization", typeof(ICloneServicesLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется поиск дублирующихся единиц кода.
        /// </summary>
        internal static string CloneSearchInProgress {
            get {
                return ResourceManager.GetString("CloneSearchInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск дублирующихся единиц кода завершён.
        /// </summary>
        internal static string CloneSearchIsDone {
            get {
                return ResourceManager.GetString("CloneSearchIsDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Построение списка файлов завершено.
        /// </summary>
        internal static string EndFilesListBuilding {
            get {
                return ResourceManager.GetString("EndFilesListBuilding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется загрузка файлов.
        /// </summary>
        internal static string LoadFilesInProgress {
            get {
                return ResourceManager.GetString("LoadFilesInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции прервано пользователем.
        /// </summary>
        internal static string OperationCancelled {
            get {
                return ResourceManager.GetString("OperationCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подождите, идёт прерывание операции.
        /// </summary>
        internal static string OperationCancellingInProgress {
            get {
                return ResourceManager.GetString("OperationCancellingInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции успешно завершено.
        /// </summary>
        internal static string OperationDoneSuccesfully {
            get {
                return ResourceManager.GetString("OperationDoneSuccesfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Идёт выполнение операции.
        /// </summary>
        internal static string OperationInProgress {
            get {
                return ResourceManager.GetString("OperationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполнение операции завершено с ошибками.
        /// </summary>
        internal static string OperationtDoneWithErrors {
            get {
                return ResourceManager.GetString("OperationtDoneWithErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выполняется построение списка файлов для обработки.
        /// </summary>
        internal static string StartFilesListBuilding {
            get {
                return ResourceManager.GetString("StartFilesListBuilding", resourceCulture);
            }
        }
    }
}
