//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IClone.ICloneImplementation.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DCSLastChoosenFolder {
            get {
                return ((string)(this["DCSLastChoosenFolder"]));
            }
            set {
                this["DCSLastChoosenFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string DCSLastChoosenFilesExtensions {
            get {
                return ((string)(this["DCSLastChoosenFilesExtensions"]));
            }
            set {
                this["DCSLastChoosenFilesExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("ru-RU")]
        public string UILanguage {
            get {
                return ((string)(this["UILanguage"]));
            }
            set {
                this["UILanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DCSMemorizeLastRunParams {
            get {
                return ((bool)(this["DCSMemorizeLastRunParams"]));
            }
            set {
                this["DCSMemorizeLastRunParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CSWMemorizeLastRunParams {
            get {
                return ((bool)(this["CSWMemorizeLastRunParams"]));
            }
            set {
                this["CSWMemorizeLastRunParams"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string CSWLastChoosenFolder {
            get {
                return ((string)(this["CSWLastChoosenFolder"]));
            }
            set {
                this["CSWLastChoosenFolder"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1251")]
        public int CSWLastChoosenEncoding {
            get {
                return ((int)(this["CSWLastChoosenEncoding"]));
            }
            set {
                this["CSWLastChoosenEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int CSWLastChoosenLanguage {
            get {
                return ((int)(this["CSWLastChoosenLanguage"]));
            }
            set {
                this["CSWLastChoosenLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("$RECYCLE.BIN; System Volume Information; .svn; _svn; Config.Msi")]
        public string CSWSkippingFolders {
            get {
                return ((string)(this["CSWSkippingFolders"]));
            }
            set {
                this["CSWSkippingFolders"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool CSWIsUseParallelExtensions {
            get {
                return ((bool)(this["CSWIsUseParallelExtensions"]));
            }
            set {
                this["CSWIsUseParallelExtensions"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CSWLastChoosenAlgorithm {
            get {
                return ((int)(this["CSWLastChoosenAlgorithm"]));
            }
            set {
                this["CSWLastChoosenAlgorithm"] = value;
            }
        }
    }
}
